# Generated by Django 6.0 on 2025-12-27 05:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the position (e.g., President)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of position responsibilities')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this position is currently accepting votes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the candidate', max_length=100)),
                ('bio', models.TextField(blank=True, help_text='Biography or campaign message')),
                ('photo_url', models.URLField(blank=True, help_text="URL to candidate's photo (optional)")),
                ('is_active', models.BooleanField(default=True, help_text='Whether this candidate is currently in the race')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.ForeignKey(help_text='Position the candidate is running for', on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='voting_api.position')),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'ordering': ['position', 'name'],
                'unique_together': {('position', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(help_text='7-digit student identification number', max_length=7, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Only numeric characters are allowed.')])),
                ('nickname', models.CharField(default='Student', help_text='Display name for the student', max_length=50)),
                ('email', models.EmailField(help_text='Unique email address for the student', max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the vote was cast')),
                ('candidate', models.ForeignKey(help_text='Candidate who received the vote', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting_api.candidate')),
                ('position', models.ForeignKey(help_text='Position for which the vote was cast', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting_api.position')),
                ('user', models.ForeignKey(help_text='User who cast the vote', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
                'ordering': ['-timestamp'],
                'unique_together': {('user', 'position')},
            },
        ),
    ]
